name: simple-logger
version: 0.1.1
synopsis: A very simple but efficient logging framework
description: A very simple but efficient logging framework
category: Logging
maintainer: Alexander Thiemann <mail@athiemann.net>
license: MIT
github: agrafix/simple-logger
extra-source-files:
  - README.md
  - package.yaml
  - stack.yaml

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - monad-logger

library:
  source-dirs: src
  dependencies:
    - fast-logger
    - text
    - mtl
  exposed-modules:
    - Control.Logger.Simple
